opt_in_rules:
- implicit_return
- force_unwrapping
- empty_count
- yoda_condition
- toggle_bool
- static_operator
- direct_return

disabled_rules:
- trailing_whitespace
- for_where

identifier_name:
  excluded:
    - i
    - j
    - id
    - x
    - y
    - z

function_body_length:
    warning: 200
    error: 500
  
line_length:
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
